# Generated by Django 2.0.5 on 2018-09-12 01:29

from django.db import migrations

def seed(apps, schema_):
    Person = apps.get_model('flux', 'Person')
    Heritage = apps.get_model('flux', 'Heritage')
    Legacy = apps.get_model('flux', 'Legacy')

    Alan = Person(name="Alan")
    email = Person(email="a386226@gmail.com")
    password = Person(password="niners")
    Alan.save()
    email.save()
    password.save()

    heritagename = Heritage(name="Tadich Grill")
    heritageadd = Heritage(address="240 California St., San Francisco, CA 94111")
    heritageyear = Heritage(yearOpened="1849")
    heritagelat = Heritage(lat=37.8077)
    heritagelon = Heritage(lon=-122.4185)
    heritageweb = Heritage(website="https://tadichgrillsf.com")
    heritagename.save()
    heritageadd.save()
    heritageyear.save()
    heritagelat.save()
    heritagelon.save()
    heritageweb.save()

    legacyname = Legacy(name="The 500 Club")
    legacyadd = Legacy(address="500 Guerrero St., San Francisco, CA 94110")
    legacyyear = Legacy(yearOpened="1964")
    legacylat = Legacy(lat=37.63025)
    legacylon = Legacy(lon=-122.424197)
    legacyweb = Legacy(website="https://www.facebook.com/pages/500-Club/208229939220755")
    legacyname.save()
    legacyadd.save()
    legacyyear.save()
    legacylat.save()
    legacylon.save()
    legacyweb.save()

def destroy(apps, schema_editor):
    Person = apps.get_model('flux', 'Person')
    Heritage = apps.get_model('flux', 'Heritage')
    Legacy = apps.get_model('flux', 'Legacy')
    Person.objects.all().delete()
    Heritage.objects.all().delete()
    Legacy.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_auto_20180912_0101'),
    ]

    operations = [
        migrations.RunPython(seed, destroy)
    ]
