# Generated by Django 2.0.5 on 2018-09-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_auto_20180912_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacy',
            name='yearOpened',
            field=models.CharField(max_length=10),
        ),
    ]
