# Generated by Django 2.0.5 on 2018-09-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_auto_20180912_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='yearOpened',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lon',
            field=models.FloatField(),
        ),
    ]
