# Generated by Django 2.0.5 on 2018-09-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0005_auto_20180912_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='lat',
            field=models.FloatField(blank=True, default=37.7749, null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='lon',
            field=models.FloatField(blank=True, default=-122.419, null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='yearOpened',
            field=models.CharField(default='1849', max_length=10),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lat',
            field=models.FloatField(blank=True, default=37.7749, null=True),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lon',
            field=models.FloatField(blank=True, default=-122.4194, null=True),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='yearOpened',
            field=models.CharField(default='1849', max_length=10),
        ),
    ]
