# Generated by Django 2.0.5 on 2018-09-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0006_auto_20180912_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='lat',
            field=models.FloatField(default=37.7749),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='lon',
            field=models.FloatField(default=-122.419),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lat',
            field=models.FloatField(default=37.7749),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lon',
            field=models.FloatField(default=-122.4194),
        ),
    ]
