# Generated by Django 2.0.5 on 2018-09-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0007_auto_20180912_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='address',
            field=models.CharField(default='San Francisco', max_length=100),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='lat',
            field=models.FloatField(default=37.7749, null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='lon',
            field=models.FloatField(default=-122.419, null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='name',
            field=models.CharField(default='Restaurant', max_length=100),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='website',
            field=models.URLField(default='https://sfgov.org/'),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='yearOpened',
            field=models.CharField(default='1849', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='address',
            field=models.CharField(default='San Francisco', max_length=100),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lat',
            field=models.FloatField(default=37.7749, null=True),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='lon',
            field=models.FloatField(default=-122.4194, null=True),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='name',
            field=models.CharField(default='Restaurant', max_length=100),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='website',
            field=models.URLField(default='https://sfgov.org/'),
        ),
        migrations.AlterField(
            model_name='legacy',
            name='yearOpened',
            field=models.CharField(default='1849', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(default='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='Password', max_length=100),
        ),
    ]
